/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/region/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Region */
        post: operations["analyze_region_api_v1_region_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/region/{region_id}/metrics/{metric_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metric Layer */
        get: operations["get_metric_layer_api_v1_region__region_id__metrics__metric_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/region/{region_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_v1_region__region_id__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Model Version */
            model_version: string;
            /** Model R Squared */
            model_r_squared: number;
            /** Model Mae */
            model_mae: number;
            /** Feature Stack Built At */
            feature_stack_built_at: string | null;
            /** Model Trained At */
            model_trained_at: string | null;
            /** N Training Pixels */
            n_training_pixels: number;
            /** Caveats */
            caveats: string;
        };
        /** InterventionResult */
        InterventionResult: {
            /** Intervention Type */
            intervention_type: string;
            /** Assumptions */
            assumptions: Record<string, never>;
            /** Region Pixel Count */
            region_pixel_count: number;
            /** Mean Improvement */
            mean_improvement: number;
            /** Ranked Locations */
            ranked_locations: components["schemas"]["RankedLocation"][];
            /**
             * Grid Geojson
             * @description FeatureCollection over the whole region with before_score/after_score per cell.
             */
            grid_geojson: Record<string, never>;
            /** Aggregated */
            aggregated: boolean;
            /** Aggregation Cell Size Meters */
            aggregation_cell_size_meters?: number | null;
        };
        /** MetricLayerResponse */
        MetricLayerResponse: {
            /** Region Id */
            region_id: string;
            /** Metric Name */
            metric_name: string;
            /** Grid Geojson */
            grid_geojson: Record<string, never>;
            /** Caveats */
            caveats: string;
        };
        /** MetricStats */
        MetricStats: {
            /** Mean */
            mean: number;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Std */
            std: number;
        };
        /** RankedLocation */
        RankedLocation: {
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
            /** Before Score */
            before_score: number;
            /** After Score */
            after_score: number;
            /** Improvement */
            improvement: number;
        };
        /** RegionAnalyzeRequest */
        RegionAnalyzeRequest: {
            /**
             * Region
             * @description A GeoJSON Polygon or MultiPolygon geometry drawn by the user on the frontend map.
             */
            region: Record<string, never>;
        };
        /** RegionAnalyzeResponse */
        RegionAnalyzeResponse: {
            /** Region Id */
            region_id: string;
            /** Pixel Count */
            pixel_count: number;
            /**
             * Aggregated
             * @description True if the returned grid was coarsened from native 10m because the region was large.
             */
            aggregated: boolean;
            /** Aggregation Cell Size Meters */
            aggregation_cell_size_meters?: number | null;
            /** Metrics Summary */
            metrics_summary: {
                [key: string]: components["schemas"]["MetricStats"];
            };
            heat_vulnerability_summary: components["schemas"]["MetricStats"];
            /**
             * Grid Geojson
             * @description FeatureCollection of grid cells with per-cell metric values and heat_vulnerability_score.
             */
            grid_geojson: Record<string, never>;
            /** Shap Summary */
            shap_summary: components["schemas"]["ShapContribution"][];
            /** Plain Language Summary */
            plain_language_summary: string;
            /** Caveats */
            caveats: string;
        };
        /** ShapContribution */
        ShapContribution: {
            /** Feature */
            feature: string;
            /** Mean Shap Value */
            mean_shap_value: number;
        };
        /** SimulateRequest */
        SimulateRequest: {
            /**
             * Intervention Types
             * @description One or more of: add_tree_cover, cool_roof, add_green_space
             */
            intervention_types: string[];
            /**
             * Top N
             * @default 10
             */
            top_n: number;
        };
        /** SimulateResponse */
        SimulateResponse: {
            /** Region Id */
            region_id: string;
            /** Results */
            results: components["schemas"]["InterventionResult"][];
            /** Caveats */
            caveats: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_region_api_v1_region_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metric_layer_api_v1_region__region_id__metrics__metric_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
                metric_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricLayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_v1_region__region_id__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
